class ClubStructures {
  final int complexo;
  final int ct;
  final int base;
  final int scout;
  final int financeiro;
  final int marketing;
  final int comunicacao;
  final int medico;
  final int estadio;

  const ClubStructures({
    required this.complexo,
    required this.ct,
    required this.base,
    required this.scout,
    required this.financeiro,
    required this.marketing,
    required this.comunicacao,
    required this.medico,
    required this.estadio,
  });

  double get structuralPower {
    final total = complexo +
        ct +
        base +
        scout +
        financeiro +
        marketing +
        comunicacao +
        medico +
        estadio;
    return total / 9.0;
  }
}

class ClubStructuresCatalog {
  const ClubStructuresCatalog._();

  static const Map<String, ClubStructures> all = {
    // =========================================================
    // SÉRIE A
    // =========================================================

    'BRA01': ClubStructures(
      complexo: 7,
      ct: 6,
      base: 5,
      scout: 5,
      financeiro: 5,
      marketing: 5,
      comunicacao: 5,
      medico: 6,
      estadio: 6,
    ),
    'BRA02': ClubStructures(
      complexo: 7,
      ct: 7,
      base: 5,
      scout: 6,
      financeiro: 7,
      marketing: 6,
      comunicacao: 6,
      medico: 6,
      estadio: 5,
    ),
    'BRA03': ClubStructures(
      complexo: 6,
      ct: 6,
      base: 6,
      scout: 6,
      financeiro: 6,
      marketing: 6,
      comunicacao: 5,
      medico: 5,
      estadio: 5,
    ),
    'BRA04': ClubStructures(
      complexo: 6,
      ct: 6,
      base: 4,
      scout: 6,
      financeiro: 5,
      marketing: 5,
      comunicacao: 5,
      medico: 4,
      estadio: 5,
    ),
    'BRA05': ClubStructures(
      complexo: 6,
      ct: 5,
      base: 4,
      scout: 6,
      financeiro: 6,
      marketing: 4,
      comunicacao: 4,
      medico: 5,
      estadio: 4,
    ),
    'BRA06': ClubStructures(
      complexo: 7,
      ct: 5,
      base: 6,
      scout: 5,
      financeiro: 4,
      marketing: 7,
      comunicacao: 5,
      medico: 7,
      estadio: 7,
    ),
    'BRA07': ClubStructures(
      complexo: 5,
      ct: 3,
      base: 4,
      scout: 4,
      financeiro: 3,
      marketing: 3,
      comunicacao: 3,
      medico: 4,
      estadio: 4,
    ),
    'BRA08': ClubStructures(
      complexo: 7,
      ct: 6,
      base: 7,
      scout: 7,
      financeiro: 7,
      marketing: 6,
      comunicacao: 5,
      medico: 6,
      estadio: 6,
    ),
    'BRA09': ClubStructures(
      complexo: 5,
      ct: 3,
      base: 3,
      scout: 4,
      financeiro: 4,
      marketing: 4,
      comunicacao: 4,
      medico: 3,
      estadio: 3,
    ),
    'BRA10': ClubStructures(
      complexo: 7,
      ct: 7,
      base: 7,
      scout: 7,
      financeiro: 7,
      marketing: 7,
      comunicacao: 6,
      medico: 6,
      estadio: 7,
    ),
    'BRA11': ClubStructures(
      complexo: 7,
      ct: 5,
      base: 7,
      scout: 6,
      financeiro: 6,
      marketing: 6,
      comunicacao: 6,
      medico: 5,
      estadio: 6,
    ),
    'BRA12': ClubStructures(
      complexo: 6,
      ct: 5,
      base: 5,
      scout: 6,
      financeiro: 5,
      marketing: 6,
      comunicacao: 6,
      medico: 6,
      estadio: 5,
    ),
    'BRA13': ClubStructures(
      complexo: 7,
      ct: 5,
      base: 6,
      scout: 6,
      financeiro: 5,
      marketing: 6,
      comunicacao: 7,
      medico: 5,
      estadio: 7,
    ),
    'BRA14': ClubStructures(
      complexo: 7,
      ct: 5,
      base: 7,
      scout: 6,
      financeiro: 4,
      marketing: 5,
      comunicacao: 5,
      medico: 5,
      estadio: 7,
    ),
    'BRA15': ClubStructures(
      complexo: 4,
      ct: 4,
      base: 4,
      scout: 4,
      financeiro: 4,
      marketing: 4,
      comunicacao: 4,
      medico: 4,
      estadio: 4,
    ),
    'BRA16': ClubStructures(
      complexo: 8,
      ct: 8,
      base: 7,
      scout: 7,
      financeiro: 7,
      marketing: 7,
      comunicacao: 7,
      medico: 6,
      estadio: 7,
    ),
    'BRA17': ClubStructures(
      complexo: 7,
      ct: 6,
      base: 6,
      scout: 6,
      financeiro: 5,
      marketing: 5,
      comunicacao: 5,
      medico: 4,
      estadio: 7,
    ),
    'BRA18': ClubStructures(
      complexo: 7,
      ct: 4,
      base: 6,
      scout: 6,
      financeiro: 4,
      marketing: 7,
      comunicacao: 6,
      medico: 5,
      estadio: 6,
    ),
    'BRA19': ClubStructures(
      complexo: 4,
      ct: 4,
      base: 4,
      scout: 4,
      financeiro: 4,
      marketing: 4,
      comunicacao: 4,
      medico: 4,
      estadio: 4,
    ),
    'BRA20': ClubStructures(
      complexo: 4,
      ct: 4,
      base: 4,
      scout: 4,
      financeiro: 4,
      marketing: 4,
      comunicacao: 4,
      medico: 4,
      estadio: 4,
    ),

    // =========================================================
    // SÉRIE B
    // =========================================================

    'BRB21': ClubStructures(
      complexo: 5,
      ct: 3,
      base: 3,
      scout: 3,
      financeiro: 4,
      marketing: 4,
      comunicacao: 4,
      medico: 4,
      estadio: 4,
    ),
    'BRB22': ClubStructures(
      complexo: 5,
      ct: 3,
      base: 4,
      scout: 3,
      financeiro: 3,
      marketing: 3,
      comunicacao: 3,
      medico: 3,
      estadio: 4,
    ),
    'BRB23': ClubStructures(
      complexo: 4,
      ct: 3,
      base: 3,
      scout: 2,
      financeiro: 3,
      marketing: 3,
      comunicacao: 3,
      medico: 3,
      estadio: 3,
    ),
    'BRB24': ClubStructures(
      complexo: 3,
      ct: 3,
      base: 3,
      scout: 3,
      financeiro: 3,
      marketing: 3,
      comunicacao: 3,
      medico: 3,
      estadio: 1,
    ),
    'BRB25': ClubStructures(
      complexo: 6,
      ct: 5,
      base: 4,
      scout: 5,
      financeiro: 4,
      marketing: 4,
      comunicacao: 4,
      medico: 4,
      estadio: 5,
    ),
    'BRB26': ClubStructures(
      complexo: 6,
      ct: 5,
      base: 5,
      scout: 5,
      financeiro: 5,
      marketing: 5,
      comunicacao: 5,
      medico: 5,
      estadio: 4,
    ),
    'BRB27': ClubStructures(
      complexo: 4,
      ct: 3,
      base: 4,
      scout: 3,
      financeiro: 3,
      marketing: 3,
      comunicacao: 2,
      medico: 3,
      estadio: 3,
    ),
    'BRB28': ClubStructures(
      complexo: 5,
      ct: 4,
      base: 4,
      scout: 5,
      financeiro: 4,
      marketing: 4,
      comunicacao: 4,
      medico: 5,
      estadio: 4,
    ),
    'BRB29': ClubStructures(
      complexo: 5,
      ct: 3,
      base: 5,
      scout: 3,
      financeiro: 3,
      marketing: 3,
      comunicacao: 2,
      medico: 3,
      estadio: 5,
    ),
    'BRB30': ClubStructures(
      complexo: 5,
      ct: 3,
      base: 5,
      scout: 4,
      financeiro: 4,
      marketing: 3,
      comunicacao: 2,
      medico: 3,
      estadio: 3,
    ),
    'BRB31': ClubStructures(
      complexo: 5,
      ct: 5,
      base: 4,
      scout: 5,
      financeiro: 4,
      marketing: 4,
      comunicacao: 4,
      medico: 5,
      estadio: 4,
    ),
    'BRB32': ClubStructures(
      complexo: 6,
      ct: 5,
      base: 5,
      scout: 5,
      financeiro: 4,
      marketing: 5,
      comunicacao: 5,
      medico: 3,
      estadio: 4,
    ),
    'BRB33': ClubStructures(
      complexo: 4,
      ct: 4,
      base: 4,
      scout: 4,
      financeiro: 3,
      marketing: 4,
      comunicacao: 4,
      medico: 4,
      estadio: 2,
    ),
    'BRB34': ClubStructures(
      complexo: 5,
      ct: 4,
      base: 5,
      scout: 4,
      financeiro: 4,
      marketing: 3,
      comunicacao: 3,
      medico: 4,
      estadio: 4,
    ),
    'BRB35': ClubStructures(
      complexo: 5,
      ct: 3,
      base: 5,
      scout: 3,
      financeiro: 3,
      marketing: 3,
      comunicacao: 2,
      medico: 3,
      estadio: 5,
    ),
    'BRB36': ClubStructures(
      complexo: 7,
      ct: 6,
      base: 7,
      scout: 5,
      financeiro: 3,
      marketing: 6,
      comunicacao: 4,
      medico: 4,
      estadio: 6,
    ),
    'BRB37': ClubStructures(
      complexo: 5,
      ct: 5,
      base: 5,
      scout: 4,
      financeiro: 4,
      marketing: 4,
      comunicacao: 3,
      medico: 3,
      estadio: 5,
    ),
    'BRB38': ClubStructures(
      complexo: 3,
      ct: 3,
      base: 3,
      scout: 3,
      financeiro: 3,
      marketing: 3,
      comunicacao: 3,
      medico: 3,
      estadio: 3,
    ),
    'BRB39': ClubStructures(
      complexo: 3,
      ct: 2,
      base: 3,
      scout: 2,
      financeiro: 3,
      marketing: 2,
      comunicacao: 3,
      medico: 2,
      estadio: 3,
    ),
    'BRB40': ClubStructures(
      complexo: 6,
      ct: 5,
      base: 5,
      scout: 5,
      financeiro: 5,
      marketing: 5,
      comunicacao: 5,
      medico: 4,
      estadio: 5,
    ),

    // =========================================================
    // SÉRIE C
    // =========================================================

    'BRC41': ClubStructures(
      complexo: 3,
      ct: 3,
      base: 2,
      scout: 2,
      financeiro: 3,
      marketing: 2,
      comunicacao: 3,
      medico: 2,
      estadio: 2,
    ),
    'BRC42': ClubStructures(
      complexo: 3,
      ct: 2,
      base: 3,
      scout: 2,
      financeiro: 3,
      marketing: 2,
      comunicacao: 3,
      medico: 2,
      estadio: 3,
    ),
    'BRC43': ClubStructures(
      complexo: 3,
      ct: 2,
      base: 2,
      scout: 3,
      financeiro: 2,
      marketing: 2,
      comunicacao: 3,
      medico: 2,
      estadio: 2,
    ),
    'BRC44': ClubStructures(
      complexo: 3,
      ct: 2,
      base: 2,
      scout: 3,
      financeiro: 2,
      marketing: 2,
      comunicacao: 3,
      medico: 2,
      estadio: 2,
    ),
    'BRC45': ClubStructures(
      complexo: 3,
      ct: 3,
      base: 2,
      scout: 2,
      financeiro: 3,
      marketing: 2,
      comunicacao: 3,
      medico: 2,
      estadio: 2,
    ),
    'BRC46': ClubStructures(
      complexo: 3,
      ct: 2,
      base: 1,
      scout: 3,
      financeiro: 2,
      marketing: 1,
      comunicacao: 3,
      medico: 2,
      estadio: 1,
    ),
    'BRC47': ClubStructures(
      complexo: 2,
      ct: 2,
      base: 2,
      scout: 2,
      financeiro: 2,
      marketing: 2,
      comunicacao: 2,
      medico: 2,
      estadio: 2,
    ),
    'BRC48': ClubStructures(
      complexo: 5,
      ct: 2,
      base: 2,
      scout: 2,
      financeiro: 1,
      marketing: 2,
      comunicacao: 2,
      medico: 3,
      estadio: 4,
    ),
    'BRC49': ClubStructures(
      complexo: 2,
      ct: 2,
      base: 2,
      scout: 2,
      financeiro: 2,
      marketing: 2,
      comunicacao: 2,
      medico: 2,
      estadio: 2,
    ),
    'BRC50': ClubStructures(
      complexo: 3,
      ct: 2,
      base: 2,
      scout: 3,
      financeiro: 2,
      marketing: 2,
      comunicacao: 3,
      medico: 2,
      estadio: 2,
    ),
    'BRC51': ClubStructures(
      complexo: 5,
      ct: 3,
      base: 3,
      scout: 2,
      financeiro: 2,
      marketing: 2,
      comunicacao: 2,
      medico: 3,
      estadio: 3,
    ),
    'BRC52': ClubStructures(
      complexo: 2,
      ct: 2,
      base: 1,
      scout: 2,
      financeiro: 2,
      marketing: 1,
      comunicacao: 2,
      medico: 2,
      estadio: 1,
    ),
    'BRC53': ClubStructures(
      complexo: 2,
      ct: 2,
      base: 2,
      scout: 2,
      financeiro: 2,
      marketing: 2,
      comunicacao: 2,
      medico: 2,
      estadio: 2,
    ),
    'BRC54': ClubStructures(
      complexo: 3,
      ct: 2,
      base: 1,
      scout: 3,
      financeiro: 2,
      marketing: 1,
      comunicacao: 3,
      medico: 2,
      estadio: 1,
    ),
    'BRC55': ClubStructures(
      complexo: 4,
      ct: 3,
      base: 2,
      scout: 3,
      financeiro: 2,
      marketing: 3,
      comunicacao: 2,
      medico: 3,
      estadio: 2,
    ),
    'BRC56': ClubStructures(
      complexo: 4,
      ct: 3,
      base: 4,
      scout: 3,
      financeiro: 3,
      marketing: 4,
      comunicacao: 4,
      medico: 4,
      estadio: 1,
    ),
    'BRC57': ClubStructures(
      complexo: 3,
      ct: 2,
      base: 1,
      scout: 3,
      financeiro: 2,
      marketing: 1,
      comunicacao: 3,
      medico: 2,
      estadio: 1,
    ),
    'BRC58': ClubStructures(
      complexo: 2,
      ct: 2,
      base: 1,
      scout: 2,
      financeiro: 2,
      marketing: 1,
      comunicacao: 2,
      medico: 2,
      estadio: 1,
    ),
    'BRC59': ClubStructures(
      complexo: 2,
      ct: 1,
      base: 2,
      scout: 2,
      financeiro: 1,
      marketing: 2,
      comunicacao: 2,
      medico: 1,
      estadio: 2,
    ),
    'BRC60': ClubStructures(
      complexo: 2,
      ct: 2,
      base: 1,
      scout: 2,
      financeiro: 2,
      marketing: 1,
      comunicacao: 2,
      medico: 2,
      estadio: 1,
    ),

    // =========================================================
    // SÉRIE D
    // =========================================================

    'BRD61': ClubStructures(
      complexo: 3,
      ct: 3,
      base: 2,
      scout: 3,
      financeiro: 2,
      marketing: 2,
      comunicacao: 2,
      medico: 2,
      estadio: 3,
    ),
    'BRD62': ClubStructures(
      complexo: 2,
      ct: 2,
      base: 1,
      scout: 2,
      financeiro: 2,
      marketing: 1,
      comunicacao: 2,
      medico: 2,
      estadio: 1,
    ),
    'BRD63': ClubStructures(
      complexo: 3,
      ct: 2,
      base: 1,
      scout: 3,
      financeiro: 2,
      marketing: 1,
      comunicacao: 3,
      medico: 2,
      estadio: 1,
    ),
    'BRD64': ClubStructures(
      complexo: 3,
      ct: 2,
      base: 1,
      scout: 3,
      financeiro: 2,
      marketing: 1,
      comunicacao: 3,
      medico: 2,
      estadio: 1,
    ),
    'BRD65': ClubStructures(
      complexo: 3,
      ct: 2,
      base: 1,
      scout: 3,
      financeiro: 2,
      marketing: 1,
      comunicacao: 3,
      medico: 2,
      estadio: 1,
    ),
    'BRD66': ClubStructures(
      complexo: 3,
      ct: 2,
      base: 2,
      scout: 3,
      financeiro: 2,
      marketing: 1,
      comunicacao: 3,
      medico: 2,
      estadio: 1,
    ),
    'BRD67': ClubStructures(
      complexo: 3,
      ct: 2,
      base: 2,
      scout: 3,
      financeiro: 2,
      marketing: 1,
      comunicacao: 3,
      medico: 2,
      estadio: 1,
    ),
    'BRD68': ClubStructures(
      complexo: 2,
      ct: 2,
      base: 1,
      scout: 2,
      financeiro: 2,
      marketing: 1,
      comunicacao: 2,
      medico: 2,
      estadio: 1,
    ),
    'BRD69': ClubStructures(
      complexo: 3,
      ct: 2,
      base: 3,
      scout: 2,
      financeiro: 3,
      marketing: 2,
      comunicacao: 3,
      medico: 2,
      estadio: 3,
    ),
    'BRD70': ClubStructures(
      complexo: 2,
      ct: 1,
      base: 1,
      scout: 2,
      financeiro: 1,
      marketing: 1,
      comunicacao: 2,
      medico: 1,
      estadio: 1,
    ),
    'BRD71': ClubStructures(
      complexo: 2,
      ct: 1,
      base: 1,
      scout: 1,
      financeiro: 2,
      marketing: 2,
      comunicacao: 1,
      medico: 1,
      estadio: 1,
    ),
    'BRD72': ClubStructures(
      complexo: 4,
      ct: 2,
      base: 3,
      scout: 1,
      financeiro: 1,
      marketing: 2,
      comunicacao: 2,
      medico: 2,
      estadio: 2,
    ),
    'BRD73': ClubStructures(
      complexo: 2,
      ct: 2,
      base: 1,
      scout: 2,
      financeiro: 2,
      marketing: 1,
      comunicacao: 2,
      medico: 2,
      estadio: 1,
    ),
    'BRD74': ClubStructures(
      complexo: 3,
      ct: 1,
      base: 1,
      scout: 2,
      financeiro: 2,
      marketing: 2,
      comunicacao: 2,
      medico: 1,
      estadio: 2,
    ),
    'BRD75': ClubStructures(
      complexo: 2,
      ct: 1,
      base: 1,
      scout: 1,
      financeiro: 2,
      marketing: 1,
      comunicacao: 1,
      medico: 1,
      estadio: 2,
    ),
    'BRD76': ClubStructures(
      complexo: 3,
      ct: 2,
      base: 1,
      scout: 2,
      financeiro: 2,
      marketing: 1,
      comunicacao: 2,
      medico: 2,
      estadio: 1,
    ),
    'BRD77': ClubStructures(
      complexo: 2,
      ct: 2,
      base: 1,
      scout: 2,
      financeiro: 2,
      marketing: 1,
      comunicacao: 1,
      medico: 1,
      estadio: 1,
    ),
    'BRD78': ClubStructures(
      complexo: 3,
      ct: 2,
      base: 2,
      scout: 3,
      financeiro: 2,
      marketing: 1,
      comunicacao: 3,
      medico: 2,
      estadio: 2,
    ),
    'BRD79': ClubStructures(
      complexo: 2,
      ct: 1,
      base: 1,
      scout: 1,
      financeiro: 1,
      marketing: 2,
      comunicacao: 1,
      medico: 1,
      estadio: 1,
    ),
    'BRD80': ClubStructures(
      complexo: 2,
      ct: 1,
      base: 1,
      scout: 1,
      financeiro: 1,
      marketing: 2,
      comunicacao: 1,
      medico: 2,
      estadio: 1,
    ),
  };

  static ClubStructures byId(String id) {
    return all[id] ??
        const ClubStructures(
          complexo: 1,
          ct: 1,
          base: 1,
          scout: 1,
          financeiro: 1,
          marketing: 1,
          comunicacao: 1,
          medico: 1,
          estadio: 1,
        );
  }

  static bool containsId(String id) {
    return all.containsKey(id);
  }
}
