🏆 Série A (1–20)
1.	Atlético Belo Horizonte (Atlético Mineiro)
2.	Vila dos Pinheiros (Athletico Paranaense)
3.	Baiano (Bahia)
4.	João Pereira Souza (Botafogo)
5.	Bragança-Paulista (Bragantino)
6.	Operarios-Paulista (Corinthians)
7.	Rio Criciúma- (Criciúma)
8.	Celeste-BH (Cruzeiro)
9.	Cuiabano (Cuiabá)
10.	Rubro-Rio (Flamengo)
11.	Vale das Laranjeiras (Fluminense)
12.	Forte assunção-CE (Fortaleza)
13.	Grêmio-Eldorado (Grêmio)
14.	Inter-Guaiba (Internacional)
15.	Verde-da-Serra (Juventude)
16.	Palestra-Itália (Palmeiras)
17.	São Vicente  (São Paulo)
18.	Cruz-Maltino (Vasco)
19.	Vera Cruz (Vitória)
20.	Atlético-Vila Boa (Atlético Goianiense)
________________________________________
🥈 Série B (21–40)
21.	Cidade de Minas (América Mineiro)
22.	Independência da Ilha  (Avaí)
23.	Vila Tibério (Botafogo-SP)
24.	São Luiz Gonzaga (Brusque)
25.	Cearense (mantido)
26.	Chapecó (Chapecoense)
27.	Alagoas FC (CRB)
28.	Goiano (Goiás)
29.	Il Guarany-Campinas (Guarani)
30.	Atlética Sorocabana (Ituano)
31.	Matarona (mantido)
32.	Novo-Horizonte (Novorizontino)
33.	Proletário-Paraná (Operário-PR)
34.	Papão (Paysandu)
35.	Ponte da Fumaça-Campinas (Ponte Preta)
36.	Villa de Santos (Santos)
37.	Recife (Sport)
38.	Tombo-Minas (Tombense)
39.	Vila-Goiás (Vila Nova)
40.	Curitiba (Coritiba)
________________________________________
🥉 Série C (41–60)
41.	Rio Grande Do Norte (ABC)
42.	Amazonas-Norte (Amazonas FC)
43.	Aparecida-GO (Aparecidense)
44.	João Pessoa (Botafogo-PB)
45.	Real Alagoano (CSA)
46.	Dragão-Sergipano (Confiança)
47.	Ferrim-Ceará (Ferroviário)
48.	Velha Figueira-SC (Figueirense)
49.	Florestal (Floresta)
50.	Londrinense (Londrina)
51.	Capibaribe-PE (Náutico)
52.	Azulão-Pará (Remo)
53.	Bernardo-SP (São Bernardo)
54.	Real Zeca (São José-RS)
55.	Roraima FC (São Raimundo-RR)
56.	Tombo  (Substituto fictício)
57.	Arraial Rio (Volta Redonda)
58.	Erechim (Ypiranga-RS)
59.	Rio Negro-AM (Manaus FC)
60.	São Jose dos Altos-PI (Altos)
________________________________________
🔘 Série D (61–80)
61.	Caxiense(Caxias)
62.	Caruaruense (Central de Caruaru)
63.	Araraguara-SP (Ferroviária)
64.	Aguia Branca (Real Noroeste)
65.	Governador Valadares (Democrata GV)
66.	Uniclinic (Atlético Cearense)
67.	Paranaense (Paraná Clube)
68.	Campina-PB (Campinense)
69.	Nova Amsterdã (América-RN)
70.	São Luís (Moto Club)
71.	Feira-BA (Bahia de Feira)
72.	Desportos-SP (Portuguesa)
73.	Juazeiro do norte (Juazeirense)
74.	Camaragibe (Retrô FC)
75.	Ingazeira (Afogados)
76.	Caldas -MG (Caldense)
77.	Maracapá (Trem)
78.	Brasilia-capital (Brasiliense)
79.	Nacional Manaus  (Fast Clube)
80.	1920-AC (Rio Branco)
